version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - PORT_NUMBER=5432
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_HOST
    # command: uvicorn src.app.main:app --reload
    command: >
      sh -c "while ! pg_isready -h ${DB_HOST} -p 5432 -d ${DB_NAME} -U ${DB_USER}; do sleep 1; done &&
             python src/app/run_migrations.py &&
             uvicorn src.app.main:app --reload"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      retries: 5

volumes:
  redis_data:
